apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | trunc 4 }}-mediawiki-deployment
  labels:
    app: mediawiki
{{ toYaml .Values.label | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
{{ toYaml .Values.label | indent 6 }}
  template:
    metadata:
      labels:
        app: mediawiki
{{ toYaml .Values.label | indent 8 }}
    spec:
      containers:
      - name: mediawiki
        image: {{ .Values.mediawiki.image }}
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: true
        env:
          - name: MEDIAWIKI_DB_NAME
            value: {{ .Values.env.MEDIAWIKI_DB_NAME | quote }}
          - name: MEDIAWIKI_DB_HOST
            value: {{ .Values.env.MEDIAWIKI_DB_HOST | quote }}
          - name: MEDIAWIKI_DB_PORT
            value: {{ .Values.env.MEDIAWIKI_DB_PORT | quote }}
        resources:
          limits:
            cpu: {{ .Values.resources.mediawiki.limits.cpu }}
            memory: {{ .Values.resources.mediawiki.limits.memory }}
          requests:
            cpu: {{ .Values.resources.mediawiki.requests.cpu }}
            memory: {{ .Values.resources.mediawiki.requests.memory }}
