{{- if .Values.storage }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name | trunc 4 }}-mysql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: {{ .Values.nfs.path }}
    server: {{ .Values.nfs.server }}
  persistentVolumeReclaimPolicy: Retain
{{- end }}