apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mediawiki-gp-x
spec:
  host: mediawiki-gp-x.apps.openshift.kakor.ovh
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: argocd-server
    weight: 100
  wildcardPolicy: None
